apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-nombre-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/default-storage/go-nombre
    type: DirectoryOrCreate